version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stats/service
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=rootdb
      - SPRING_DATASOURCE_PASSWORD=rootdb


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=rootdb
      - POSTGRES_PASSWORD=rootdb

  ewm-main:
    ports:
      - "8080:8080"
    build: main-service
    container_name: ewm-main
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=rootdb
      - SPRING_DATASOURCE_PASSWORD=rootdb

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=rootdb
      - POSTGRES_PASSWORD=rootdb
